# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloWorld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloWorld.proto\x12\nhelloworld\"$\n\x11HelloWorldRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"&\n\x12HelloWorldResponse\x12\x10\n\x08response\x18\x01 \x01(\t2V\n\nHelloWorld\x12H\n\x05Print\x12\x1d.helloworld.HelloWorldRequest\x1a\x1e.helloworld.HelloWorldResponse\"\x00\x42\x0fZ\rhelloworldpb/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloWorld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\rhelloworldpb/'
  _globals['_HELLOWORLDREQUEST']._serialized_start=32
  _globals['_HELLOWORLDREQUEST']._serialized_end=68
  _globals['_HELLOWORLDRESPONSE']._serialized_start=70
  _globals['_HELLOWORLDRESPONSE']._serialized_end=108
  _globals['_HELLOWORLD']._serialized_start=110
  _globals['_HELLOWORLD']._serialized_end=196
# @@protoc_insertion_point(module_scope)
