# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import youtube_dl_pb2 as youtube__dl__pb2


class GetVideoInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideo = channel.unary_unary(
                '/youtube_dl.GetVideoInfoService/GetVideo',
                request_serializer=youtube__dl__pb2.GetVideoInfoRequest.SerializeToString,
                response_deserializer=youtube__dl__pb2.GetVideoInfoResponse.FromString,
                )


class GetVideoInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetVideoInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideo,
                    request_deserializer=youtube__dl__pb2.GetVideoInfoRequest.FromString,
                    response_serializer=youtube__dl__pb2.GetVideoInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'youtube_dl.GetVideoInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetVideoInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/youtube_dl.GetVideoInfoService/GetVideo',
            youtube__dl__pb2.GetVideoInfoRequest.SerializeToString,
            youtube__dl__pb2.GetVideoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
